const express = require('express')
const router = express.Router()
const adminController = require('../controllers/adminController')
const { verifyAdminToken } = require('../middleware/auth')
const { adminLoginLimiter, destructiveActionLimiter } = require('../middleware/rateLimiters')

router.post('/api/admin', adminLoginLimiter, adminController.adminLogin)
router.post('/api/verify', verifyAdminToken, adminController.verifyUser)
router.get('/api/getUsers', verifyAdminToken, adminController.getUsers)
router.post('/api/fundwallet', verifyAdminToken, adminController.fundWallet)
router.post('/api/debitwallet', verifyAdminToken, adminController.debitWallet)
router.post('/api/deleteUser', verifyAdminToken, destructiveActionLimiter, adminController.deleteUser)
router.post('/api/deleteTrader', verifyAdminToken, destructiveActionLimiter, adminController.deleteTrader)
router.post('/api/admin/restoreUser', verifyAdminToken, adminController.restoreUser)
router.post('/api/admin/restoreTrader', verifyAdminToken, adminController.restoreTrader)
router.get('/api/admin/deletedUsers', verifyAdminToken, adminController.deletedUsers)
router.get('/api/admin/deletedTraders', verifyAdminToken, adminController.deletedTraders)
router.get('/api/admin/auditlog', verifyAdminToken, adminController.auditLog)
router.post('/api/upgradeUser', verifyAdminToken, adminController.upgradeUser)
router.post('/api/updateTraderLog', verifyAdminToken, adminController.updateTraderLog)
router.post('/api/distributeProfit', verifyAdminToken, adminController.distributeProfit)
router.post('/api/getWithdrawInfo', verifyAdminToken, adminController.getWithdrawInfo)
router.post('/api/admin/approveKYC', verifyAdminToken, adminController.approveKYC)
router.post('/api/admin/rejectKYC', verifyAdminToken, adminController.rejectKYC)

module.exports = router
